title = "IL随记"
theme = "hyde"
publishDir = "docs"
hasCJKLanguage = true
summaryLength = 100

[services]
  [services.disqus]
    shortname = 'illuzsblog'
  [services.googleAnalytics]
    id = 'G-L6RWMNY4C6'

[params]
    description = "流水帐而已，随手写写"
    layoutReverse = true
    theme = "hyde"
    themeColor = "theme-base-09"
    toc = "tocbot"

    dateTimeFormat = "2006/01/02 15:04"
    postDir = "post"

    [params.author]
        email = 'hcbabitong@gmail.com'
        name = 'IlluZ'

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/illuz/"},
  ]

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']