title = "IL随记"
theme = "hyde"
publishDir = "docs"
summaryLength = 4

[services]
  [services.disqus]
    shortname = 'illuz'

[params]
    description = "随手写写"
    googleAnalytics = ""
    layoutReverse = true
    theme = "hyde"
    themeColor = "theme-base-84"
    toc = "tocbot"


[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/illuz/"},
  ]